import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import AuthContextProvider from "./context/Auth";
import NavBar from "./NavBar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer theme='colored'/>
      <AuthContextProvider>
        <NavBar/>
        {children}  

      </AuthContextProvider>
       
        </body>
    </html>
  );
}
